from src.exceptions.handler import CustomException


class UserException(CustomException):
    pass
